language: php

php:
  - '7.4'
  - nightly

services:
  - mysql
  - postgresql

env:
  - DB=mysql
  - DB=pgsql

matrix:
    allow_failures:
        - php: nightly
    fast_finish: true

before_script:
  - wget https://www.phing.info/get/phing-latest.phar && mv phing-latest.phar phing && chmod +x phing
  - composer selfupdate --no-progress
  - travis_retry composer install --prefer-dist
  - mkdir tests/_temp
  - "sh -c \"if [ '$DB' = 'mysql' ]; then cp tests/_helpers/mysql.neon tests/tests.local.neon; fi\""
  - "sh -c \"if [ '$DB' = 'pgsql' ]; then cp tests/_helpers/pgsql.neon tests/tests.local.neon; fi\""

script:
  - ./phing test

after_failure:
  # Print *.actual content
  - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

notifications:
  email: false

cache:
  directories:
    - $HOME/.composer/cache
    - vendor
