name: Tests
on:
  - push
  - pull_request

jobs:
  tests_mysql:
    name: Tests on MySql
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - '7.4'
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: tests
        ports:
          - 3306:3306
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer, phing
          coverage: pcov
      - run: mkdir tests/_temp
      - run: cp tests/_helpers/mysql.neon tests/tests.local.neon
      - run: composer install --prefer-dist --no-progress --no-interaction
      - run: phing test
